name: Infrastructure Deployment

on:
  push:
    branches:
      - main  # Trigger on main branch commits
  workflow_dispatch:  # Allows manual trigger

permissions:
  id-token: write  # For OIDC authentication
  contents: read

jobs:
  terraform:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Debug OIDC Tokens
      run: |
        echo "GitHub Actions OIDC Token:"
        curl -sSL -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com"

      env:
        ACTIONS_ID_TOKEN_REQUEST_TOKEN: ${{ secrets.ACTIONS_ID_TOKEN_REQUEST_TOKEN }}
        ACTIONS_ID_TOKEN_REQUEST_URL: ${{ secrets.ACTIONS_ID_TOKEN_REQUEST_URL }}
      
    - name: Test Assume Role
      run: |
        ROLE_ARN="arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GithubActionsRole"
        TOKEN=$(curl -sS -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL" | jq -r '.value')
          
        echo "Attempting to assume role: $ROLE_ARN"
          
        RESPONSE=$(curl -sS -X POST "https://sts.amazonaws.com" \
          -H "Content-Type: application/x-www-form-urlencoded" \
          -d "Action=AssumeRoleWithWebIdentity" \
          -d "RoleArn=$ROLE_ARN" \
          -d "RoleSessionName=GitHubActionsSession" \
          -d "WebIdentityToken=$TOKEN" \
          -d "Version=2011-06-15")
          
        echo "AWS STS Response:"
        echo "$RESPONSE"

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GithubActionsRole
        aws-region: us-east-1
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: $${{ secrets.AWS_SECRET_ACCESS_KEY }}
        audience: sts.amazonaws.com

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: latest

    - name: Terraform Init
      run: |
        cd infrastructure
        terraform init

    - name: Terraform Format Check
      run: |
        cd infrastructure
        terraform fmt -check

    - name: Terraform Plan
      run: |
        cd infrastructure
        terraform plan -out=tfplan

    - name: Terraform Apply (Manual Approval Required)
      run: |
        cd infrastructure
        terraform apply -auto-approve tfplan
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
