name: Infrastructure Deployment

on:
  push:
    paths:
      - 'infrastructure/**'  # Run only when infra files change
    branches:
      - main  # Trigger on main branch commits
  workflow_dispatch:  # Allows manual trigger

permissions:
  id-token: write  # For OIDC authentication
  contents: read

jobs:
  terraform:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GithubActionsRole
        aws-region: us-east-1
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: $${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: latest

    - name: Terraform Init
      run: |
        cd infrastructure
        terraform init

    - name: Terraform Format Check
      run: |
        cd infrastructure
        terraform fmt -check

    - name: Terraform Plan
      run: |
        cd infrastructure
        terraform plan -out=tfplan

    - name: Terraform Apply (Manual Approval Required)
      run: |
        cd infrastructure
        terraform apply -auto-approve tfplan
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
